project_id = "tksfdvnogzsweteetjjw"

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.razorpay-orders]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.fetch-partner-ratings]
verify_jwt = false

[functions.courier-recommendation-assistant]
verify_jwt = false

[functions.google-geocode-pincode]
verify_jwt = false

[functions.calculate-platform-fee]
verify_jwt = false

[functions.saved-addresses]
verify_jwt = false

[functions.razorpay-refund]
verify_jwt = false
