project_id = "tksfdvnogzsweteetjjw"

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.razorpay-orders]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true
