project_id = "tksfdvnogzsweteetjjw"

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.razorpay-orders]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.fetch-partner-ratings]
verify_jwt = false

[functions.courier-recommendation-assistant]
verify_jwt = false

[functions.google-geocode-pincode]
verify_jwt = false

[functions.calculate-platform-fee]
verify_jwt = false

[functions.saved-addresses]
verify_jwt = false

[functions.razorpay-refund]
verify_jwt = false

[functions.shadowfax-serviceability]
verify_jwt = false

[functions.shadowfax-booking]
verify_jwt = false

[functions.shadowfax-tracking]
verify_jwt = false

[functions.shadowfax-cancel-order]
verify_jwt = false

[functions.prayog-cancel-order]
verify_jwt = false

[functions.fix-address]
verify_jwt = false

[functions.predict-eta]
verify_jwt = false

[functions.get-user-orders]
verify_jwt = false

[functions.delhivery-serviceability]
verify_jwt = false
